// Generated by scripts/gen-abi.ts from protocol/contracts/out/PasskeyAccountFactory.sol/PasskeyAccountFactory.json. Do not edit.
export const passkeyAccountFactoryAbi = [
  {
    type: "constructor",
    inputs: [
      {
        name: "entryPoint",
        type: "address",
        internalType: "contract IEntryPoint",
      },
      {
        name: "solidityP256",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "IMPLEMENTATION",
    inputs: [],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "contract PasskeyAccount",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createAccount",
    inputs: [
      {
        name: "qx",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "qy",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "salt",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "account",
        type: "address",
        internalType: "contract PasskeyAccount",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getAddress",
    inputs: [
      {
        name: "qx",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "qy",
        type: "bytes32",
        internalType: "bytes32",
      },
      {
        name: "salt",
        type: "bytes32",
        internalType: "bytes32",
      },
    ],
    outputs: [
      {
        name: "",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AccountCreated",
    inputs: [
      {
        name: "account",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "qx",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "qy",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
      {
        name: "salt",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
  {
    type: "error",
    name: "FailedDeployment",
    inputs: [],
  },
  {
    type: "error",
    name: "InsufficientBalance",
    inputs: [
      {
        name: "balance",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "needed",
        type: "uint256",
        internalType: "uint256",
      },
    ],
  },
] as const;
