// Regenerates src/*.ts from Foundry artifacts. Run after `forge build`: pnpm gen:abi (root: pnpm gen:abi).
// Output is committed so TypeScript consumers and CI never need the Solidity toolchain.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "..", "..", "protocol", "contracts", "out");
const srcDir = join(here, "..", "src");
mkdirSync(srcDir, { recursive: true });

// USDCPaymaster -> usdcPaymaster, TestUSDC -> testUSDC, EntryPoint -> entryPoint
const camel = (n: string) => n.replace(/^[A-Z]+(?=[A-Z][a-z]|$)|^[A-Z]/, (m) => m.toLowerCase());
const contracts = [
  "TestUSDC",
  "PasskeyAccount",
  "PasskeyAccountFactory",
  "USDCPaymaster",
  "EntryPoint",
  "NetworkVersion",
  "StableSwapPool",
];
const exportsList: string[] = [];
for (const name of contracts) {
  const artifact = JSON.parse(
    readFileSync(join(outDir, `${name}.sol`, `${name}.json`), "utf8"),
  ) as { abi: unknown[] };
  const ident = `${camel(name)}Abi`;
  writeFileSync(
    join(srcDir, `${name}.ts`),
    `// Generated by scripts/gen-abi.ts from protocol/contracts/out/${name}.sol/${name}.json. Do not edit.\nexport const ${ident} = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`,
  );
  exportsList.push(`export { ${ident} } from "./${name}.js";`);
  console.log(`wrote src/${name}.ts (${artifact.abi.length} entries)`);
}
writeFileSync(
  join(srcDir, "index.ts"),
  `${exportsList.join("\n")}\nexport { linethRollupAbi } from "./LinethRollup.js";\n`,
);
